### ISSUE TITLE
xdrgen breaks using gluster's .x files

### ISSUE THREAD

**Issue by cholcombe973** [kofemann/pynfs#1]
I tried running xdrgen.py against the https://github.com/gluster/glusterfs/blob/master/rpc/xdr/src/cli1-xdr.x file and it gave up with this error:

```
Input file is /home/chris/repos/glusterfs/rpc/xdr/src/cli1-xdr.x
Will use output files cli1-xdr_const.py, cli1-xdr_type.py, and cli1-xdr_pack.py
yacc: Generating LALR parsing table...
Syntax error at ',' (lineno 3)
Traceback (most recent call last):
  File "/home/chris/repos/pynfs/xdr/xdrgen.py", line 1471, in <module>
    run(sys.argv[1])
  File "/home/chris/repos/pynfs/xdr/xdrgen.py", line 1413, in run
    yacc.parse(data, debug=debug)
  File "/home/chris/repos/pynfs/xdr/ply/yacc.py", line 303, in parse
    p.func(pslice)
  File "/home/chris/repos/pynfs/xdr/xdrgen.py", line 555, in p_enum_constant
    value = t[3]
  File "/home/chris/repos/pynfs/xdr/ply/yacc.py", line 121, in __getitem__
    if n >= 0: return self.slice[n].value
IndexError: list index out of range
```

I haven't dug into why this is happening just yet but I plan on doing so shortly.

**Comment by cholcombe973** [comment]
Here's the parser.out file:
https://gist.github.com/cholcombe973/c74b499f44265f80f881
