### ISSUE TITLE
The code sequence of nfs4.1/xdrdef/nfs4_const.py is incurrent

### ISSUE THREAD

**Issue by Sn0rt** [kofemann/pynfs#4]
**Desc**
Some of the variables be used before they are defined.
The issue may be attribute to sequence of nfs4_const.py  generated by ply/yacc.py
And the code sequence of nfs4_const.py is difference regenerated by yacc.py at everytime.

**Env**
python: python 2.7
os: rhel7.1 rhel7.2 rhel6.7

**Reproduce step:**
```shell
root@ ~~/pynfs/nfs4.1# grep -rn LAYOUT4_RET_REC_FSID xdrdef/nfs4_const.py
grep -rn LAYOUT4_RET_REC_FSID xdrdef/nfs4_const.py
12:LAYOUTRECALL4_FSID = LAYOUT4_RET_REC_FSID
118:LAYOUTRETURN4_FSID = LAYOUT4_RET_REC_FSID
479:LAYOUT4_RET_REC_FSID = 2
716:    LAYOUT4_RET_REC_FSID : 'LAYOUTRECALL4_FSID',
865:    LAYOUT4_RET_REC_FSID : 'LAYOUTRETURN4_FSID',

Traceback (most recent call last):
  File "./nfs4server.py", line 4, in <module>
    import nfs4lib
  File "/root/bz1232402-RHEL6-NFS4-client-kernel-panic-in/pynfs/nfs4.1/nfs4lib.py", line 3, in <module>
    import xdrdef.nfs4_const
  File "/root/bz1232402-RHEL6-NFS4-client-kernel-panic-in/pynfs/nfs4.1/xdrdef/nfs4_const.py", line 12, in <module>
    LAYOUTRECALL4_FSID = LAYOUT4_RET_REC_FSID
NameError: name 'LAYOUT4_RET_REC_FSID' is not defined
[16:37:04 root@ ~~/pynfs/nfs4.1]# python2.7 ./nfs4server.py --use_files --reset  &
Traceback (most recent call last):
  File "./nfs4server.py", line 4, in <module>
    import nfs4lib
  File "/root/bz1232402-RHEL6-NFS4-client-kernel-panic-in/pynfs/nfs4.1/nfs4lib.py", line 3, in <module>
    import xdrdef.nfs4_const
  File "/root/bz1232402-RHEL6-NFS4-client-kernel-panic-in/pynfs/nfs4.1/xdrdef/nfs4_const.py", line 12, in <module>
    LAYOUTRECALL4_FSID = LAYOUT4_RET_REC_FSID
NameError: name 'LAYOUT4_RET_REC_FSID' is not defined

**Comment by SergeyLysanov** [comment]
@Sn0rt 
Hello!
I have the same problem. Do you know the solution?

**Comment by Sn0rt** [comment]
>Hello!
I have the same problem. Do you know the solution?

I can't slove this promble, and use a AWK script to fix it temporarily.

**Comment by kofemann** [comment]
Did you run 
**python setup.py build**

after git pull?
