### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GSS_S_COMPLETE'

### ISSUE THREAD

**Issue by abhi2196** [kofemann/pynfs#5]
Env
python: python 2.7
os: ubuntu 16.04 server

abhishek-vm@abhi-VM:~/pynfs$ ./setup.py build

Moving to ply
running build
running build_py

Moving to xdr
running build
running build_py
running build_scripts

Moving to gssapi
running build
running build_ext
running build_py

Moving to rpc
running build
running build_py
Input file is rpc.x
Will use output files rpc_const.py, rpc_type.py, and rpc_pack.py
Input file is gss.x
Will use output files gss_const.py, gss_type.py, and gss_pack.py
copying gss_pack.py -> build/lib.linux-x86_64-2.7/rpc
copying gss_type.py -> build/lib.linux-x86_64-2.7/rpc
copying rpc_type.py -> build/lib.linux-x86_64-2.7/rpc
copying gss_const.py -> build/lib.linux-x86_64-2.7/rpc
copying rpc_const.py -> build/lib.linux-x86_64-2.7/rpc
copying rpc_pack.py -> build/lib.linux-x86_64-2.7/rpc

Moving to nfs4.1
running build
running build_py
expand = ''
xdrdir = '/home/abhishek-vm/pynfs/nfs4.1/xdrdef'
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/pnfs_block.x
Will use output files pnfs_block_const.py, pnfs_block_type.py, and pnfs_block_pack.py
yacc: Generating LALR parsing table...
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/portmap.x
Will use output files portmap_const.py, portmap_type.py, and portmap_pack.py
yacc: Generating LALR parsing table...
Ignoring program PMAP_PROG = 100000
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/mnt3.x
Will use output files mnt3_const.py, mnt3_type.py, and mnt3_pack.py
yacc: Generating LALR parsing table...
Ignoring program MOUNT_PROGRAM = 100005
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/nfs4.x
Will use output files nfs4_const.py, nfs4_type.py, and nfs4_pack.py
yacc: Generating LALR parsing table...
Ignoring program NFS4_PROGRAM = 100003
Ignoring program NFS4_CALLBACK = 0x40000000L
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/sctrl.x
Will use output files sctrl_const.py, sctrl_type.py, and sctrl_pack.py
yacc: Generating LALR parsing table...
Input file is /home/abhishek-vm/pynfs/nfs4.1/xdrdef/nfs3.x
Will use output files nfs3_const.py, nfs3_type.py, and nfs3_pack.py
yacc: Generating LALR parsing table...
Ignoring program NFS_PROGRAM = 100003
expand = 'server41tests'
xdrdir = '/home/abhishek-vm/pynfs/nfs4.1/server41tests/xdrdef'

Moving to nfs4.0
Traceback (most recent call last):
  File "./setup.py", line 83, in <module>
    from testserver import VERSION
  File "/home/abhishek-vm/pynfs/nfs4.0/testserver.py", line 38, in <module>
    import nfs4lib
  File "/home/abhishek-vm/pynfs/nfs4.0/nfs4lib.py", line 29, in <module>
    import rpc
  File "/home/abhishek-vm/pynfs/nfs4.0/lib/rpc/__init__.py", line 1, in <module>
    from rpc import *
  File "/home/abhishek-vm/pynfs/nfs4.0/lib/rpc/rpc.py", line 27, in <module>
    from rpcsec.sec_auth_gss import SecAuthGss
  File "/home/abhishek-vm/pynfs/nfs4.0/lib/rpc/rpcsec/sec_auth_gss.py", line 7, in <module>
    import gssapi
  File "/home/abhishek-vm/pynfs/nfs4.0/lib/rpc/rpcsec/gssapi.py", line 52, in <module>
    GSS_S_COMPLETE = _gssapi.GSS_S_COMPLETE
AttributeError: 'module' object has no attribute 'GSS_S_COMPLETE'

**Comment by abhi2196** [comment]
removing  pynfs/nfs4.0/lib/rpc/rpcsec/gssapi.py file solved the problem.
